[server_config]
    bind_addr = ":8080"
    log_level = "debug"
    session_key = "[session_key]"

[camera_config]

[servo_config]
    gpio_x = 12
    gpio_y = 19
    inverse_x = true
    inverse_y = false

[user_store]
    auth_file = "users.json"
    new_user_key = "1"
